[2022-01-29 14:08:02,549] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-01-29 14:08:02,594] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-01-29 14:08:02,595] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:08:02,595] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:08:02,595] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:08:02,648] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2021-02-02 06:00:00+00:00
[2022-01-29 14:08:02,654] {standard_task_runner.py:52} INFO - Started process 403 to run task
[2022-01-29 14:08:02,659] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2021-02-02T06:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpvidwmb2l', '--error-file', '/tmp/tmpum97uqey']
[2022-01-29 14:08:02,660] {standard_task_runner.py:77} INFO - Job 43: Subtask get_data
[2022-01-29 14:08:02,866] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2021-02-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:08:03,109] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2021-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-02T06:00:00+00:00
[2022-01-29 14:08:03,112] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:08:03,114] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:08:03,145] {subprocess.py:85} INFO - Output:
[2022-01-29 14:08:03,148] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:08:03,149] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:08:03,243] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20210202T060000, start_date=20220129T140802, end_date=20220129T140803
[2022-01-29 14:08:03,345] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:08:03,491] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:53:13,141] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-01-30 10:53:13,212] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-01-30 10:53:13,213] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:53:13,213] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:53:13,213] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:53:13,302] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2021-02-02 06:00:00+00:00
[2022-01-30 10:53:13,349] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2021-02-02T06:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmphqlo7jk5', '--error-file', '/tmp/tmp6gs_n1nk']
[2022-01-30 10:53:13,350] {standard_task_runner.py:77} INFO - Job 88: Subtask get_data
[2022-01-30 10:53:13,341] {standard_task_runner.py:52} INFO - Started process 1067 to run task
[2022-01-30 10:53:13,682] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2021-02-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:53:13,895] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:53:13,984] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2021-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-02T06:00:00+00:00
[2022-01-30 10:53:13,987] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:53:13,988] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-02.csv > /opt/***output_2021-02.csv']
[2022-01-30 10:53:14,025] {subprocess.py:85} INFO - Output:
[2022-01-30 10:53:37,998] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:53:38,255] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20210202T060000, start_date=20220130T105313, end_date=20220130T105338
[2022-01-30 10:53:38,360] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:53:38,470] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
