[2022-01-29 14:02:07,376] {processor.py:163} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:02:07,388] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:02:07,388] {logging_mixin.py:109} INFO - [2022-01-29 14:02:07,388] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:02:07,399] {logging_mixin.py:109} INFO - [2022-01-29 14:02:07,395] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 6, in <module>
    from black import schedule_formatting
ModuleNotFoundError: No module named 'black'
[2022-01-29 14:02:07,430] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:02:07,442] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.072 seconds
[2022-01-29 14:02:37,751] {processor.py:163} INFO - Started process (PID=61) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:02:37,752] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:02:37,753] {logging_mixin.py:109} INFO - [2022-01-29 14:02:37,753] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:02:37,756] {logging_mixin.py:109} INFO - [2022-01-29 14:02:37,755] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 6, in <module>
    from black import schedule_formatting
ModuleNotFoundError: No module named 'black'
[2022-01-29 14:02:37,887] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:02:37,939] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.193 seconds
[2022-01-29 14:03:08,507] {processor.py:163} INFO - Started process (PID=81) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:03:08,511] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:03:08,512] {logging_mixin.py:109} INFO - [2022-01-29 14:03:08,512] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:03:08,518] {logging_mixin.py:109} INFO - [2022-01-29 14:03:08,516] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 6, in <module>
    from black import schedule_formatting
ModuleNotFoundError: No module named 'black'
[2022-01-29 14:03:08,562] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:03:08,591] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.089 seconds
[2022-01-29 14:03:39,063] {processor.py:163} INFO - Started process (PID=101) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:03:39,066] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:03:39,068] {logging_mixin.py:109} INFO - [2022-01-29 14:03:39,068] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:03:39,074] {logging_mixin.py:109} INFO - [2022-01-29 14:03:39,072] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 6, in <module>
    from black import schedule_formatting
ModuleNotFoundError: No module named 'black'
[2022-01-29 14:03:39,114] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:03:39,138] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.082 seconds
[2022-01-29 14:04:09,526] {processor.py:163} INFO - Started process (PID=120) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:04:09,528] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:04:09,530] {logging_mixin.py:109} INFO - [2022-01-29 14:04:09,530] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:04:09,534] {logging_mixin.py:109} INFO - [2022-01-29 14:04:09,533] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 6, in <module>
    from black import schedule_formatting
ModuleNotFoundError: No module named 'black'
[2022-01-29 14:04:09,574] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:04:09,604] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.084 seconds
[2022-01-29 14:04:39,837] {processor.py:163} INFO - Started process (PID=140) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:04:39,840] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:04:39,841] {logging_mixin.py:109} INFO - [2022-01-29 14:04:39,841] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:04:39,846] {logging_mixin.py:109} INFO - [2022-01-29 14:04:39,845] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 6, in <module>
    from black import schedule_formatting
ModuleNotFoundError: No module named 'black'
[2022-01-29 14:04:39,883] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:04:39,905] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.074 seconds
[2022-01-29 14:05:10,258] {processor.py:163} INFO - Started process (PID=161) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:05:10,260] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:05:10,262] {logging_mixin.py:109} INFO - [2022-01-29 14:05:10,262] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:05:10,268] {logging_mixin.py:109} INFO - [2022-01-29 14:05:10,267] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 6, in <module>
    from black import schedule_formatting
ModuleNotFoundError: No module named 'black'
[2022-01-29 14:05:10,307] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:05:10,329] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.077 seconds
[2022-01-29 14:05:40,944] {processor.py:163} INFO - Started process (PID=182) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:05:40,947] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:05:40,948] {logging_mixin.py:109} INFO - [2022-01-29 14:05:40,948] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:05:40,954] {logging_mixin.py:109} INFO - [2022-01-29 14:05:40,952] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 6, in <module>
    from black import schedule_formatting
ModuleNotFoundError: No module named 'black'
[2022-01-29 14:05:40,989] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:05:41,015] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.076 seconds
[2022-01-29 14:05:54,156] {processor.py:163} INFO - Started process (PID=192) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:05:54,161] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:05:54,162] {logging_mixin.py:109} INFO - [2022-01-29 14:05:54,162] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:05:54,224] {logging_mixin.py:109} INFO - [2022-01-29 14:05:54,222] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 29, in <module>
    bash_command = 'print("helloworld!!")'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['python_callable'] is required
[2022-01-29 14:05:54,262] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:05:54,286] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.139 seconds
[2022-01-29 14:06:24,506] {processor.py:163} INFO - Started process (PID=213) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:06:24,509] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:06:24,510] {logging_mixin.py:109} INFO - [2022-01-29 14:06:24,510] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:06:24,542] {logging_mixin.py:109} INFO - [2022-01-29 14:06:24,539] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 29, in <module>
    bash_command = 'print("helloworld!!")'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 177, in apply_defaults
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Argument ['python_callable'] is required
[2022-01-29 14:06:24,631] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:06:24,714] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.215 seconds
[2022-01-29 14:06:52,845] {processor.py:163} INFO - Started process (PID=224) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:06:52,848] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:06:52,850] {logging_mixin.py:109} INFO - [2022-01-29 14:06:52,849] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:06:52,977] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:07:11,813] {logging_mixin.py:109} INFO - [2022-01-29 14:07:11,813] {manager.py:496} INFO - Created Permission View: can edit on DAG:HomeWorkWeek2
[2022-01-29 14:07:11,849] {logging_mixin.py:109} INFO - [2022-01-29 14:07:11,848] {manager.py:496} INFO - Created Permission View: can read on DAG:HomeWorkWeek2
[2022-01-29 14:07:11,850] {logging_mixin.py:109} INFO - [2022-01-29 14:07:11,849] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:07:11,877] {logging_mixin.py:109} INFO - [2022-01-29 14:07:11,876] {dag.py:2415} INFO - Creating ORM DAG for HomeWorkWeek2
[2022-01-29 14:07:11,916] {logging_mixin.py:109} INFO - [2022-01-29 14:07:11,916] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2019-01-02 06:00:00+00:00
[2022-01-29 14:07:11,956] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 19.117 seconds
[2022-01-29 14:07:42,211] {processor.py:163} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:07:42,214] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:07:42,216] {logging_mixin.py:109} INFO - [2022-01-29 14:07:42,215] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:07:42,290] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:07:42,319] {logging_mixin.py:109} INFO - [2022-01-29 14:07:42,319] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:07:42,374] {logging_mixin.py:109} INFO - [2022-01-29 14:07:42,374] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2020-01-02T06:00:00+00:00
[2022-01-29 14:07:42,400] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.195 seconds
[2022-01-29 14:08:12,536] {processor.py:163} INFO - Started process (PID=282) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:08:12,538] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:08:12,540] {logging_mixin.py:109} INFO - [2022-01-29 14:08:12,539] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:08:12,634] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:08:12,673] {logging_mixin.py:109} INFO - [2022-01-29 14:08:12,673] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:08:12,750] {logging_mixin.py:109} INFO - [2022-01-29 14:08:12,749] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2021-11-02T06:00:00+00:00
[2022-01-29 14:08:12,783] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.255 seconds
[2022-01-29 14:08:43,100] {processor.py:163} INFO - Started process (PID=301) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:08:43,105] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:08:43,107] {logging_mixin.py:109} INFO - [2022-01-29 14:08:43,106] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:08:43,197] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:08:43,225] {logging_mixin.py:109} INFO - [2022-01-29 14:08:43,225] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:08:43,289] {logging_mixin.py:109} INFO - [2022-01-29 14:08:43,289] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:08:43,314] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.220 seconds
[2022-01-29 14:09:13,403] {processor.py:163} INFO - Started process (PID=322) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:09:13,405] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:09:13,406] {logging_mixin.py:109} INFO - [2022-01-29 14:09:13,406] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:09:13,478] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:09:13,503] {logging_mixin.py:109} INFO - [2022-01-29 14:09:13,503] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:09:13,556] {logging_mixin.py:109} INFO - [2022-01-29 14:09:13,556] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:09:13,582] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.185 seconds
[2022-01-29 14:09:43,832] {processor.py:163} INFO - Started process (PID=342) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:09:43,835] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:09:43,837] {logging_mixin.py:109} INFO - [2022-01-29 14:09:43,837] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:09:43,916] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:09:43,939] {logging_mixin.py:109} INFO - [2022-01-29 14:09:43,939] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:09:43,998] {logging_mixin.py:109} INFO - [2022-01-29 14:09:43,998] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:09:44,027] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.202 seconds
[2022-01-29 14:10:14,296] {processor.py:163} INFO - Started process (PID=362) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:10:14,298] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:10:14,300] {logging_mixin.py:109} INFO - [2022-01-29 14:10:14,300] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:10:14,371] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:10:14,397] {logging_mixin.py:109} INFO - [2022-01-29 14:10:14,397] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:10:14,457] {logging_mixin.py:109} INFO - [2022-01-29 14:10:14,456] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:10:14,480] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.190 seconds
[2022-01-29 14:10:44,804] {processor.py:163} INFO - Started process (PID=383) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:10:44,808] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:10:44,810] {logging_mixin.py:109} INFO - [2022-01-29 14:10:44,810] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:10:44,893] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:10:44,918] {logging_mixin.py:109} INFO - [2022-01-29 14:10:44,918] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:10:44,983] {logging_mixin.py:109} INFO - [2022-01-29 14:10:44,982] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:10:45,006] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.209 seconds
[2022-01-29 14:11:15,095] {processor.py:163} INFO - Started process (PID=404) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:11:15,098] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:11:15,100] {logging_mixin.py:109} INFO - [2022-01-29 14:11:15,099] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:11:15,176] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:11:15,202] {logging_mixin.py:109} INFO - [2022-01-29 14:11:15,201] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:11:15,263] {logging_mixin.py:109} INFO - [2022-01-29 14:11:15,263] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:11:15,288] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.199 seconds
[2022-01-29 14:11:45,516] {processor.py:163} INFO - Started process (PID=423) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:11:45,520] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:11:45,521] {logging_mixin.py:109} INFO - [2022-01-29 14:11:45,521] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:11:45,596] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:11:45,621] {logging_mixin.py:109} INFO - [2022-01-29 14:11:45,621] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:11:45,672] {logging_mixin.py:109} INFO - [2022-01-29 14:11:45,672] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:11:45,697] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.187 seconds
[2022-01-29 14:12:16,125] {processor.py:163} INFO - Started process (PID=441) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:12:16,128] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:12:16,131] {logging_mixin.py:109} INFO - [2022-01-29 14:12:16,130] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:12:16,222] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:12:16,255] {logging_mixin.py:109} INFO - [2022-01-29 14:12:16,255] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:12:16,319] {logging_mixin.py:109} INFO - [2022-01-29 14:12:16,319] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:12:16,346] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.226 seconds
[2022-01-29 14:12:46,389] {processor.py:163} INFO - Started process (PID=462) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:12:46,392] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:12:46,393] {logging_mixin.py:109} INFO - [2022-01-29 14:12:46,392] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:12:46,442] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:12:46,472] {logging_mixin.py:109} INFO - [2022-01-29 14:12:46,472] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:12:46,518] {logging_mixin.py:109} INFO - [2022-01-29 14:12:46,518] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:12:46,537] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.151 seconds
[2022-01-29 14:13:16,844] {processor.py:163} INFO - Started process (PID=482) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:13:16,847] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:13:16,848] {logging_mixin.py:109} INFO - [2022-01-29 14:13:16,848] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:13:16,918] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:13:16,945] {logging_mixin.py:109} INFO - [2022-01-29 14:13:16,945] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:13:17,011] {logging_mixin.py:109} INFO - [2022-01-29 14:13:17,011] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:13:17,036] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.199 seconds
[2022-01-29 14:13:47,215] {processor.py:163} INFO - Started process (PID=502) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:13:47,218] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:13:47,221] {logging_mixin.py:109} INFO - [2022-01-29 14:13:47,220] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:13:47,327] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:13:47,357] {logging_mixin.py:109} INFO - [2022-01-29 14:13:47,357] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:13:47,417] {logging_mixin.py:109} INFO - [2022-01-29 14:13:47,417] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:13:47,442] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.234 seconds
[2022-01-29 14:14:17,692] {processor.py:163} INFO - Started process (PID=512) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:14:17,695] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:14:17,697] {logging_mixin.py:109} INFO - [2022-01-29 14:14:17,696] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:14:17,796] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:14:17,825] {logging_mixin.py:109} INFO - [2022-01-29 14:14:17,825] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:14:17,894] {logging_mixin.py:109} INFO - [2022-01-29 14:14:17,893] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:14:17,916] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.230 seconds
[2022-01-29 14:14:48,053] {processor.py:163} INFO - Started process (PID=533) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:14:48,056] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:14:48,058] {logging_mixin.py:109} INFO - [2022-01-29 14:14:48,057] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:14:48,146] {processor.py:654} INFO - DAG(s) dict_keys(['HomeWorkWeek2']) retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:14:48,177] {logging_mixin.py:109} INFO - [2022-01-29 14:14:48,176] {dag.py:2396} INFO - Sync 1 DAGs
[2022-01-29 14:14:48,246] {logging_mixin.py:109} INFO - [2022-01-29 14:14:48,246] {dag.py:2935} INFO - Setting next_dagrun for HomeWorkWeek2 to 2022-01-02T06:00:00+00:00
[2022-01-29 14:14:48,269] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.223 seconds
[2022-01-29 14:19:59,058] {processor.py:163} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:19:59,059] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:19:59,060] {logging_mixin.py:109} INFO - [2022-01-29 14:19:59,060] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:19:59,744] {logging_mixin.py:109} INFO - [2022-01-29 14:19:59,743] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:19:59,771] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:19:59,771] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:19:59,782] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 0.727 seconds
[2022-01-29 14:20:30,040] {processor.py:163} INFO - Started process (PID=65) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:20:30,042] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:20:30,043] {logging_mixin.py:109} INFO - [2022-01-29 14:20:30,043] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:20:31,314] {logging_mixin.py:109} INFO - [2022-01-29 14:20:31,312] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:20:31,347] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:20:31,370] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 1.334 seconds
[2022-01-29 14:21:01,563] {processor.py:163} INFO - Started process (PID=90) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:21:01,566] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:21:01,569] {logging_mixin.py:109} INFO - [2022-01-29 14:21:01,568] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:21:03,031] {logging_mixin.py:109} INFO - [2022-01-29 14:21:03,029] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:21:03,065] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:21:03,089] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 1.531 seconds
[2022-01-29 14:21:33,256] {processor.py:163} INFO - Started process (PID=115) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:21:33,260] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:21:33,263] {logging_mixin.py:109} INFO - [2022-01-29 14:21:33,262] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:21:34,637] {logging_mixin.py:109} INFO - [2022-01-29 14:21:34,634] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:21:34,679] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:21:34,705] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 1.457 seconds
[2022-01-29 14:22:05,137] {processor.py:163} INFO - Started process (PID=139) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:22:05,140] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:22:05,142] {logging_mixin.py:109} INFO - [2022-01-29 14:22:05,141] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:22:06,566] {logging_mixin.py:109} INFO - [2022-01-29 14:22:06,563] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:22:06,603] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:22:06,628] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 1.497 seconds
[2022-01-29 14:22:37,033] {processor.py:163} INFO - Started process (PID=164) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:22:37,036] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:22:37,038] {logging_mixin.py:109} INFO - [2022-01-29 14:22:37,038] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:22:38,362] {logging_mixin.py:109} INFO - [2022-01-29 14:22:38,358] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:22:38,420] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:22:38,450] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 1.423 seconds
[2022-01-29 14:23:08,736] {processor.py:163} INFO - Started process (PID=188) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:23:08,740] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:23:08,742] {logging_mixin.py:109} INFO - [2022-01-29 14:23:08,741] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:23:10,174] {logging_mixin.py:109} INFO - [2022-01-29 14:23:10,171] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:23:10,206] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:23:10,229] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 1.498 seconds
[2022-01-29 14:23:40,706] {processor.py:163} INFO - Started process (PID=212) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:23:40,710] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:23:40,712] {logging_mixin.py:109} INFO - [2022-01-29 14:23:40,711] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:23:42,194] {logging_mixin.py:109} INFO - [2022-01-29 14:23:42,192] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:23:42,226] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:23:42,250] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 1.552 seconds
[2022-01-29 14:24:12,370] {processor.py:163} INFO - Started process (PID=236) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:24:12,373] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:24:12,375] {logging_mixin.py:109} INFO - [2022-01-29 14:24:12,375] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:24:13,827] {logging_mixin.py:109} INFO - [2022-01-29 14:24:13,825] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:24:13,862] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:24:13,889] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 1.524 seconds
[2022-01-29 14:24:44,292] {processor.py:163} INFO - Started process (PID=260) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:24:44,296] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:24:44,298] {logging_mixin.py:109} INFO - [2022-01-29 14:24:44,297] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:24:45,726] {logging_mixin.py:109} INFO - [2022-01-29 14:24:45,724] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:24:45,758] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:24:45,780] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 1.498 seconds
[2022-01-29 14:25:16,175] {processor.py:163} INFO - Started process (PID=284) to work on /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:25:16,179] {processor.py:642} INFO - Processing file /opt/airflow/dags/dag_questions1.py for tasks to queue
[2022-01-29 14:25:16,181] {logging_mixin.py:109} INFO - [2022-01-29 14:25:16,181] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:25:17,578] {logging_mixin.py:109} INFO - [2022-01-29 14:25:17,576] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dag_questions1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_questions1.py", line 33, in <module>
    get_data >> ingest_data
NameError: name 'ingest_data' is not defined
[2022-01-29 14:25:17,611] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_questions1.py
[2022-01-29 14:25:17,633] {processor.py:171} INFO - Processing /opt/airflow/dags/dag_questions1.py took 1.464 seconds
