[2022-01-29 14:07:47,294] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-03-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:47,339] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-03-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:47,339] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:47,339] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:47,339] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:47,385] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-03-02 06:00:00+00:00
[2022-01-29 14:07:47,391] {standard_task_runner.py:52} INFO - Started process 355 to run task
[2022-01-29 14:07:47,397] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-03-02T06:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpbqivat__', '--error-file', '/tmp/tmpfue58fwt']
[2022-01-29 14:07:47,398] {standard_task_runner.py:77} INFO - Job 32: Subtask get_data
[2022-01-29 14:07:47,602] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-03-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:47,806] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-02T06:00:00+00:00
[2022-01-29 14:07:47,809] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:47,810] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:47,827] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:47,830] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:47,831] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:47,898] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20200302T060000, start_date=20220129T140747, end_date=20220129T140747
[2022-01-29 14:07:47,961] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:48,046] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:49:42,677] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-03-02T06:00:00+00:00 [queued]>
[2022-01-30 10:49:42,746] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-03-02T06:00:00+00:00 [queued]>
[2022-01-30 10:49:42,747] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:49:42,748] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:49:42,749] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:49:42,813] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-03-02 06:00:00+00:00
[2022-01-30 10:49:42,821] {standard_task_runner.py:52} INFO - Started process 865 to run task
[2022-01-30 10:49:42,830] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-03-02T06:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpdpbearkc', '--error-file', '/tmp/tmp2vope_hz']
[2022-01-30 10:49:42,830] {standard_task_runner.py:77} INFO - Job 77: Subtask get_data
[2022-01-30 10:49:43,048] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-03-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:49:43,224] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:49:43,326] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-02T06:00:00+00:00
[2022-01-30 10:49:43,329] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:49:43,330] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-03.csv > /opt/***output_2020-03.csv']
[2022-01-30 10:49:43,364] {subprocess.py:85} INFO - Output:
[2022-01-30 10:51:53,159] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:51:53,247] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20200302T060000, start_date=20220130T104942, end_date=20220130T105153
[2022-01-30 10:51:53,328] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:51:53,429] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
