[2022-01-29 14:07:49,354] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-04-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:49,428] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-04-02T06:00:00+00:00 [queued]>
[2022-01-29 14:07:49,429] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:49,429] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 14:07:49,429] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 14:07:49,532] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-04-02 06:00:00+00:00
[2022-01-29 14:07:49,538] {standard_task_runner.py:52} INFO - Started process 358 to run task
[2022-01-29 14:07:49,546] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-04-02T06:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmprmz4du78', '--error-file', '/tmp/tmprfiuts4k']
[2022-01-29 14:07:49,548] {standard_task_runner.py:77} INFO - Job 33: Subtask get_data
[2022-01-29 14:07:49,920] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-04-02T06:00:00+00:00 [running]> on host d1e1fe005577
[2022-01-29 14:07:50,176] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-02T06:00:00+00:00
[2022-01-29 14:07:50,178] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-29 14:07:50,179] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "helloworld!!"']
[2022-01-29 14:07:50,198] {subprocess.py:85} INFO - Output:
[2022-01-29 14:07:50,199] {subprocess.py:89} INFO - helloworld!!
[2022-01-29 14:07:50,200] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-29 14:07:50,484] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20200402T060000, start_date=20220129T140749, end_date=20220129T140750
[2022-01-29 14:07:50,609] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 14:07:50,786] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-30 10:51:22,774] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-04-02T06:00:00+00:00 [queued]>
[2022-01-30 10:51:22,844] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-04-02T06:00:00+00:00 [queued]>
[2022-01-30 10:51:22,847] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:51:22,848] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 10:51:22,848] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 10:51:22,917] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): get_data> on 2020-04-02 06:00:00+00:00
[2022-01-30 10:51:22,928] {standard_task_runner.py:52} INFO - Started process 936 to run task
[2022-01-30 10:51:22,938] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'get_data', 'scheduled__2020-04-02T06:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmp2nei2bze', '--error-file', '/tmp/tmp15naqjpx']
[2022-01-30 10:51:22,939] {standard_task_runner.py:77} INFO - Job 78: Subtask get_data
[2022-01-30 10:51:23,199] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.get_data scheduled__2020-04-02T06:00:00+00:00 [running]> on host fc414ca9b482
[2022-01-30 10:51:23,455] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 10:51:23,516] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2020-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-02T06:00:00+00:00
[2022-01-30 10:51:23,519] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-30 10:51:23,525] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2020-04.csv > /opt/***output_2020-04.csv']
[2022-01-30 10:51:23,542] {subprocess.py:85} INFO - Output:
[2022-01-30 10:51:28,796] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-30 10:51:28,877] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=HomeWorkWeek2, task_id=get_data, execution_date=20200402T060000, start_date=20220130T105122, end_date=20220130T105128
[2022-01-30 10:51:28,957] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-30 10:51:29,045] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
