[2022-01-30 15:51:00,823] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.local_to_gcs_task scheduled__2021-11-02T06:00:00+00:00 [queued]>
[2022-01-30 15:51:00,869] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: HomeWorkWeek2.local_to_gcs_task scheduled__2021-11-02T06:00:00+00:00 [queued]>
[2022-01-30 15:51:00,870] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 15:51:00,870] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-30 15:51:00,870] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-30 15:51:00,910] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-11-02 06:00:00+00:00
[2022-01-30 15:51:00,924] {standard_task_runner.py:52} INFO - Started process 122 to run task
[2022-01-30 15:51:00,938] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'HomeWorkWeek2', 'local_to_gcs_task', 'scheduled__2021-11-02T06:00:00+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/dag_questions1.py', '--cfg-path', '/tmp/tmpvcxoz4xw', '--error-file', '/tmp/tmp888txibb']
[2022-01-30 15:51:00,941] {standard_task_runner.py:77} INFO - Job 287: Subtask local_to_gcs_task
[2022-01-30 15:51:01,167] {logging_mixin.py:109} INFO - Running <TaskInstance: HomeWorkWeek2.local_to_gcs_task scheduled__2021-11-02T06:00:00+00:00 [running]> on host 76a6ca5a1f6b
[2022-01-30 15:51:01,405] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-30 15:51:01,604] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=HomeWorkWeek2
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-11-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-02T06:00:00+00:00
[2022-01-30 15:51:01,671] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_fhv.py", line 40, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflowoutput_2021-11.parquet'
[2022-01-30 15:51:01,779] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=HomeWorkWeek2, task_id=local_to_gcs_task, execution_date=20211102T060000, start_date=20220130T155100, end_date=20220130T155101
[2022-01-30 15:51:01,844] {standard_task_runner.py:92} ERROR - Failed to execute job 287 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_fhv.py", line 40, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflowoutput_2021-11.parquet'
[2022-01-30 15:51:01,913] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-30 15:51:02,067] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
